### ISSUE TITLE
Change delay time to what? And rag doll question.

### ISSUE THREAD

**Issue by bencohen1992** [the1killer/sm_overview_ahk#1]
If it take some time to render it says to change the code ~101. Just wondering what a good range is... bump it up to 6000? Down?

Also, I notes there is a rag doll state command, would it be beneficial to turn your rag doll state off or will this refresh each time you are teleported to a new location/elevation?

**Comment by the1killer** [comment]
I would try adding 500 or 1000 at a time, remember that delay is for every picture which it normally generates ~414 pictures, so adding 2 seconds each adds almost 14 minutes to the render time.

I didn't mess with the ragdoll/tumble command too much. Generally TP seems to override the tumble. If needed you could add `Send, /tumble false` after the teleport command after the Sleep, 4000

**Comment by bencohen1992** [comment]
Thank you, will do.

Another question if you are willing to answer...  If I change the settings to 1080p in the .ahk, do I have to change any settings in the html?  I've attached a snapshot of my map and circled where there is magnified sections.  It also seems like all the areas have their edges cut off... a lot of roads are sliced down the center and cropped out.  Wondering if that is something I can adjust with the frame size.

Not a programmer or anything by any means but I have some experience in the sciences so I can take instructions pretty well, haha.

Thank you again for that speedy response.

**Comment by the1killer** [comment]
No shouldn't need to change anything in the html. The frame size is all in the AHK file.

Terrain height causes a lot of the things you are describing but also just perspective shift too so it will never be a perfect image, you could try adjusting the "height" parameter slightly higher or lower  if need be but that would affect every image not just certain areas.

And warehouses since they are so tall are the perfect example of this.

**Comment by the1killer** [comment]
Closing, comment here or another if you have any more questions
